### ISSUE TITLE
Warning is triggered on all characters for all sites visited

### ISSUE THREAD

**Issue by toddz262** [uxai/unicode-verifier#1]
Great idea, but it's triggering on every site I try -- including yours (subtractiv.com), Github.com, TomsGuide.com, Lifehacker.com, Stackoverflow.com, sites on local IPs, etc.

I'm on FF 116.0.3 & Win 11.

**Comment by uxai** [comment]
Hey there, there seemed to be a logic issue with the comparison. I have updated the plugin and v1.2 is available on the extensions page now. Please let me know if this works for you. I have also tested in Win 11 latest version of FF and it seems to be all good now.

Thank you for your feedback!

**Comment by toddz262** [comment]
Wow, that was quick! And that did it -- I'm no longer seeing the warning everywhere. I'm almost hoping to run into a scammy site now... ;)
